### ISSUE TITLE
Evan is dumb

### ISSUE THREAD

**Issue by LyraStobo** [Evaans11/4HC3Project#1]

**Comment by EmilyAnsell** [comment]
How do you propose we tackle this issue?

**Comment by LyraStobo** [comment]
It's a tricky one, to be sure. I don't have a solution at the moment.

**Comment by EmilyAnsell** [comment]
In that case I will close this issue for now. If anybody on the team has a suggestion that we can work with, we can reopen the issue and discuss it further.
